# Generated by Django 4.0.2 on 2022-02-19 21:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_lifter_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifter',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 2, 19, 21, 2, 16, 311520, tzinfo=utc)),
        ),
    ]
