# Generated by Django 4.0.2 on 2022-02-20 10:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_lifter_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifter',
            name='date_of_birth',
            field=models.DateField(default=datetime.datetime(2022, 2, 20, 10, 36, 10, 389730, tzinfo=utc)),
        ),
    ]
