# Generated by Django 4.0.2 on 2022-02-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_lifter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifter',
            name='workouts_per_week',
            field=models.IntegerField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (6, '7')], default=1),
        ),
    ]
