# Generated by Django 4.0.2 on 2022-02-27 10:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_lifter_workouts_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifter',
            name='height',
            field=models.SmallIntegerField(default=110, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(225)]),
        ),
        migrations.AddField(
            model_name='lifter',
            name='weight',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(200)]),
        ),
    ]
