# Generated by Django 4.0.2 on 2022-02-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_lifter_height_lifter_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifter',
            name='age',
            field=models.SmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
