# Generated by Django 4.0.3 on 2022-07-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_workout_category_exercise_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[(1, 'Cardio'), (2, 'Weighted'), (3, 'Reps')], default=1, max_length=22),
        ),
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(choices=[(1, 'Easy'), (2, 'Medium'), (3, 'Hard')], default=1, max_length=22),
        ),
    ]
