# Generated by Django 4.0.3 on 2022-07-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_exercise_workout_exset_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('1', 'Cardio'), ('2', 'Weighted'), ('3', 'Reps')], default=1, max_length=22),
        ),
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(choices=[('1', 'Easy'), ('2', 'Medium'), ('3', 'Hard')], default='Weighted', max_length=22),
        ),
    ]
