# Generated by Django 4.0.3 on 2022-07-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_workout_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
