# Generated by Django 4.0.3 on 2022-07-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_workout_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
