# Generated by Django 4.0.6 on 2022-07-31 13:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_exset_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='time_started',
            field=models.TimeField(default=datetime.datetime(2022, 7, 31, 13, 6, 45, 506500, tzinfo=utc)),
        ),
    ]
