# Generated by Django 4.0.6 on 2022-07-31 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_workout_time_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='time_started',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 31, 15, 54, 2, 670032)),
        ),
    ]
