# Generated by Django 4.0.6 on 2022-07-31 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_workout_time_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='time_started',
        ),
    ]
